import Head from 'next/head'
import Image from "next/image"
import Link from "next/link"
import { useRouter } from "next/router"

export default function Home() {
  const t = useT()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          src="/next.svg"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />

        <p>{t('someText')}</p>
        <ul>
          <li><Link href="/" locale="en">English (default)</Link></li>
          <li><Link href="/" locale="sv">Swedish</Link></li>
          <li><Link href="/robots.txt" locale="en">robots.txt</Link></li>
        </ul>
      </main>
    </>
  )
}

const strings: Record<string, Record<string, string>> = {
  en: {
    someText: "This is some English text"
  },
  sv: {
    someText: "Det här är lite text"
  }
}

function useT() {
  const {locale} = useRouter()

  return function(key: string): string {
    if (!locale) {
      return `Undefined locale <${key}>`
    }
    return strings[locale][key] || `No <$key> for locale ${locale}`
  }
}